name: CI

on:
  - pull_request

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies from npm
        run: yarn

      - name: Run tests
        run: yarn test
